<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-23T12:48:48 IST" name="Default suite" finished-at="2025-06-23T12:49:40 IST" duration-ms="51664">
    <groups>
    </groups>
    <test started-at="2025-06-23T12:48:48 IST" name="Default test" finished-at="2025-06-23T12:49:40 IST" duration-ms="51664">
      <class name="FO.testclass">
        <test-method is-config="true" signature="setup()[pri:0, instance:FO.testclass@f79e]" started-at="2025-06-23T12:48:48 IST" name="setup" finished-at="2025-06-23T12:48:51 IST" duration-ms="2789" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Test_Sucessfull_Login()[pri:0, instance:FO.testclass@f79e]" started-at="2025-06-23T12:48:51 IST" name="Test_Sucessfull_Login" finished-at="2025-06-23T12:48:57 IST" duration-ms="5960" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Sucessfull_Login -->
        <test-method signature="test_verify_current_inhouse_guests_displayed_TC_GS_01()[pri:2, instance:FO.testclass@f79e]" started-at="2025-06-23T12:48:57 IST" name="test_verify_current_inhouse_guests_displayed_TC_GS_01" finished-at="2025-06-23T12:49:39 IST" depends-on-methods="FO.testclass.Test_Sucessfull_Login" duration-ms="42057" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[❌ Reservation is not listed. Test failed.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ❌ Reservation is not listed. Test failed.
at org.testng.Assert.fail(Assert.java:111)
at FO.testclass.test_verify_current_inhouse_guests_displayed_TC_GS_01(testclass.java:2750)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_verify_current_inhouse_guests_displayed_TC_GS_01 -->
      </class> <!-- FO.testclass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
